"""add preferences to user model

Revision ID: 002bc59d212b
Revises: 957392d84f53
Create Date: 2025-08-16 22:53:19.824964

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002bc59d212b"
down_revision: Union[str, Sequence[str], None] = "957392d84f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("preferences", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferences")
    # ### end Alembic commands ###
