"""empty message

Revision ID: 70bd23d881e3
Revises: af8e8e810d54
Create Date: 2025-08-18 05:13:21.167858

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70bd23d881e3"
down_revision: Union[str, Sequence[str], None] = "af8e8e810d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_activities", sa.Column("time_spent", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_activities", "time_spent")
    # ### end Alembic commands ###
