"""empty message

Revision ID: 957392d84f53
Revises: a10640ec76d6
Create Date: 2025-08-14 15:16:35.787093

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "957392d84f53"
down_revision: Union[str, Sequence[str], None] = "a10640ec76d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "target_score", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "target_score", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
